// The bake-side provenance (voice, hashes, durations, sourceEvidence, the
// pre-bake entries) stays in the canonical city1-sentence-audio.da.json for
// scripts/aoede-bake; the app ships only this runtime projection of the
// recording fields it reads — see scripts/emit-city1-runtime-audio.mjs.
import audioManifest from '../data/city1-sentence-audio.da.runtime.json'
import upgradeAudioManifest from '../data/city1-sentence-audio.da.upgrade.runtime.json'
import germanAudioManifest from '../data/city1-sentence-audio.de.runtime.json'
import danishUpgrade from '../data/city1-review-upgrade.da.json'
import germanReview from '../data/city1-review.de.json'
import extensionBoard from '../../prototypes/finish-review/implementation/roster-extension/board-sentences.json'
import extensionReview from '../../prototypes/finish-review/implementation/roster-extension/review-sentences.json'
import board from '../../prototypes/finish-review/implementation/board-sentences.json'
import review from '../../prototypes/finish-review/implementation/review-sentences.json'
import about from '../../prototypes/finish-review/implementation/about-targets.json'
import { MAX_CLUE_NUMBER } from '../engine/config'
import { ACTIVE } from '../lang/active'
import type { Clue } from '../engine/types'

// Port of the authoring contract. Only acceptance-validated successor content
// belongs here; editorial evidence is checked at import, never invented at runtime.
export interface Span { text: string; start: number; end: number }
export interface Pair { da: string; en: string }
export interface Stage { city: 0; use: 'productive-target' | 'controlled-target' | 'preview-as-chunk' | 'receptive-ambient' }
export interface Accepted { version: number; status: 'accepted'; approval: { artifact: string; sha256: string } }
export interface BoardSentence extends Accepted {
  wordId: string; city: 0; sourceSha256: string; sentenceId: string; audioId: string
  text: Pair; wordSpan: Span
}
export interface ReviewSentence extends BoardSentence {
  targetId: string; targetStage: Stage; targetSpan: Span
}
export interface AboutTarget extends Accepted {
  targetId: string; targetStage: Stage; meaningEn: string; usageEn: string
  example: Pair; targetSpan: Span
}
export interface Envelope<T, K extends string> {
  version: 1; base: string; language: 'da'; city: 0; kind: K; rows: readonly T[]
}
export type SentenceVariant = 'normal' | 'slow'
export const SENTENCE_BAKE_RATES = { normal: 1, slow: 0.7 } as const
export interface SentenceRecording {
  audioId: string; sentenceId: string; version: number; textDa: string
  url: string; variant: SentenceVariant; bakeRate: 1 | 0.7; playbackRate: 1
}
export interface City1Catalog {
  board: readonly BoardSentence[]
  review: readonly ReviewSentence[]
  about: readonly AboutTarget[]
  recordings: readonly SentenceRecording[]
}
// Exact accepted envelopes are the single source; CI validates shapes and evidence.
// JSON imports widen literal types, hence these narrow authoring-contract casts.
/**
 * The focus upgrade of 2026-09-26 (`scripts/danish-city1-review-upgrade.mjs`)
 * replaces 29 accepted review rows at the next version, so no City 1 sentence
 * underlines an article or pronoun. The accepted envelopes stay byte-for-byte;
 * a replaced word's old row simply stops being offered, and its recordings
 * come from the upgrade's own manifest beside the frozen Aoede one.
 */
const upgraded = new Map((danishUpgrade.review as ReviewSentence[]).map(row => [row.wordId, row]))
export const DANISH_CITY1_CATALOG: City1Catalog = {
  board: [...board.rows, ...extensionBoard.rows] as BoardSentence[],
  review: ([...review.rows, ...extensionReview.rows] as ReviewSentence[]).map(row => upgraded.get(row.wordId) ?? row),
  about: [...about.rows, ...danishUpgrade.about] as AboutTarget[],
  recordings: [...audioManifest.recordings, ...upgradeAudioManifest.recordings] as SentenceRecording[],
}
/**
 * German City 1 (Flensburg), owner-approved 2026-09-26 and generated by
 * `scripts/german-city1-review.mjs`. Review rows and About notes only: the
 * dictionary keeps its own examples, so there are no board rows. The shared
 * row shape names the target-language text `da`; here it holds German.
 */
export const GERMAN_CITY1_CATALOG: City1Catalog = {
  board: [], review: germanReview.review as ReviewSentence[], about: germanReview.about as AboutTarget[],
  recordings: germanAudioManifest.recordings as SentenceRecording[],
}
const CATALOGS: Record<string, City1Catalog> = { da: DANISH_CITY1_CATALOG, de: GERMAN_CITY1_CATALOG }
/** The active route's catalogue; a language without one reviews nothing and falls back. */
export const CITY1_CATALOG: City1Catalog = CATALOGS[ACTIVE.code] ?? { board: [], review: [], about: [], recordings: [] }

export function recordingUrl(row: BoardSentence, recordings: readonly SentenceRecording[], variant: SentenceVariant = 'normal'): string | undefined {
  return recordings.find(r => r.audioId === row.audioId && r.sentenceId === row.sentenceId &&
    r.version === row.version && r.textDa === row.text.da && r.variant === variant && r.bakeRate === SENTENCE_BAKE_RATES[variant] && r.playbackRate === 1 &&
    // A row's clip lives under its own language's directory: da:mor under /audio/da/city1/.
    r.url.startsWith(`/audio/${row.wordId.slice(0, 2)}/city1/`) && !r.url.includes('..'))?.url
}
export type QueuePin = Pick<ReviewSentence, 'wordId' | 'targetId' | 'sentenceId' | 'audioId' | 'version'> & {
  clueHistoryIndex: number; clueText: string; clueNumber: number
}
export interface QueueState { version: 1; roundId: string; queue: QueuePin[]; cursor: number; dismissed: boolean }
const rowKeys = ['wordId', 'targetId', 'sentenceId', 'audioId', 'version'] as const
const validClue = (c: Clue | undefined): c is Clue => !!c && c.by === 'player' &&
  typeof c.text === 'string' && c.text.trim().length > 0 && c.text === c.text.trim() &&
  Number.isInteger(c.number) && c.number >= 1 && c.number <= MAX_CLUE_NUMBER && Array.isArray(c.guesses)
const copyPin = (p: QueuePin): QueuePin => ({ wordId: p.wordId, targetId: p.targetId,
  sentenceId: p.sentenceId, audioId: p.audioId, version: p.version,
  clueHistoryIndex: p.clueHistoryIndex, clueText: p.clueText, clueNumber: p.clueNumber })
export const dismissedQueue = (roundId: string): QueueState => ({ version: 1, roundId, queue: [], cursor: 0, dismissed: true })

export function selectQueue(history: readonly Clue[], rows: readonly ReviewSentence[], usedTargetIds: readonly string[] = []): QueuePin[] {
  const byWord = new Map(rows.map(r => [r.wordId, r]))
  const used = new Set(usedTargetIds), queue: QueuePin[] = []
  for (const [clueHistoryIndex, clue] of history.entries()) {
    if (!validClue(clue)) continue
    const candidates = clue.guesses.filter(g => g?.result === 'green').map(g => byWord.get(g.wordId)).filter((r): r is ReviewSentence => !!r)
    const row = candidates.find(r => !used.has(r.targetId)) ?? candidates[0]
    if (!row) continue
    queue.push(copyPin({ ...row, clueHistoryIndex, clueText: clue.text, clueNumber: clue.number }))
    used.add(row.targetId)
  }
  return queue
}
export function restoreQueue(saved: unknown, roundId: string, rows: readonly ReviewSentence[], history: readonly Clue[]): QueueState {
  const dismissed = dismissedQueue(roundId)
  if (!saved || typeof saved !== 'object') return dismissed
  const s = saved as QueueState
  if (s.version !== 1 || s.roundId !== roundId || s.dismissed !== false || !Array.isArray(history) ||
    !Array.isArray(s.queue) || !Number.isInteger(s.cursor) || s.cursor < 0 || s.cursor >= s.queue.length) return dismissed
  let previous = -1
  for (const pin of s.queue) {
    if (!pin || !Number.isInteger(pin.clueHistoryIndex) || pin.clueHistoryIndex <= previous) return dismissed
    const clue = history[pin.clueHistoryIndex]
    if (!validClue(clue) || pin.clueText !== clue.text || pin.clueNumber !== clue.number ||
      !clue.guesses.some(g => g?.wordId === pin.wordId && g?.result === 'green') ||
      !rows.some(r => rowKeys.every(k => r[k] === pin[k]))) return dismissed
    previous = pin.clueHistoryIndex
  }
  return { version: 1, roundId, queue: s.queue.map(copyPin), cursor: s.cursor, dismissed: false }
}
export function nextSentence(state: QueueState): QueueState {
  if (state.dismissed) return state
  const cursor = state.cursor + 1
  return cursor >= state.queue.length ? { ...state, dismissed: true } : { ...state, cursor }
}
export function resolveSentence(pin: QueuePin, rows: readonly ReviewSentence[]) {
  return rows.find(r => rowKeys.every(k => r[k] === pin[k]))
}

/** Resolve the exact row the review surface can render, not merely its cursor. */
export function currentReviewSentence(
  state: QueueState | null,
  rows: readonly ReviewSentence[],
): { pin: QueuePin; row: ReviewSentence } | null {
  if (!state || state.dismissed || !Number.isInteger(state.cursor) || state.cursor < 0) return null
  const pin = state.queue[state.cursor]
  if (!pin) return null
  const row = resolveSentence(pin, rows)
  return row ? { pin, row } : null
}

/** The next control is offered only when its saved pin resolves as well. */
export function nextReviewSentenceAvailable(
  state: QueueState | null,
  rows: readonly ReviewSentence[],
): boolean {
  if (!state || state.dismissed || !currentReviewSentence(state, rows)) return false
  const nextPin = state.queue[state.cursor + 1]
  return !!nextPin && !!resolveSentence(nextPin, rows)
}
