import { UI_LANGUAGE } from './active'

type CollectionCopy = {
  title: string; unplayed: string; cityBest: (tier: string) => string; nextPrimary: (number: number) => string
  primaryComplete: string; primaryWaiting: string; boardAria: (number: number, tier: string) => string
  pagerAria: string; details: (number: number) => string; stableId: (id: string) => string; replay: string
}

const copies: Record<string, CollectionCopy> = {
  en: { title: 'Casey’s board collection', unplayed: 'Unplayed', cityBest: tier => `City medal: ${tier}`, nextPrimary: number => `Next primary board: ${number}`, primaryComplete: 'Every primary board is complete. Improve a board with replay.', primaryWaiting: 'A replay is open. Your primary board is waiting unchanged.', boardAria: (number, tier) => `Board ${number}: ${tier}`, pagerAria: 'Board collection pages', details: number => `Board ${number} details`, stableId: id => `Stable board ID: ${id}`, replay: 'Replay this board' },
  de: { title: 'Caseys Brettsammlung', unplayed: 'Noch nicht gespielt', cityBest: tier => `Stadtmedaille: ${tier}`, nextPrimary: number => `Nächstes Hauptbrett: ${number}`, primaryComplete: 'Alle Hauptbretter sind abgeschlossen. Verbessere ein Brett im Wiederholungsspiel.', primaryWaiting: 'Eine Wiederholung ist geöffnet. Dein Hauptbrett wartet unverändert.', boardAria: (number, tier) => `Brett ${number}: ${tier}`, pagerAria: 'Seiten der Brettsammlung', details: number => `Details zu Brett ${number}`, stableId: id => `Stabile Brett-ID: ${id}`, replay: 'Dieses Brett wiederholen' },
  es: { title: 'Colección de tableros de Casey', unplayed: 'Sin jugar', cityBest: tier => `Medalla de la ciudad: ${tier}`, nextPrimary: number => `Siguiente tablero principal: ${number}`, primaryComplete: 'Todos los tableros principales están terminados. Mejora un tablero al repetirlo.', primaryWaiting: 'Hay una repetición abierta. Tu tablero principal espera sin cambios.', boardAria: (number, tier) => `Tablero ${number}: ${tier}`, pagerAria: 'Páginas de la colección de tableros', details: number => `Detalles del tablero ${number}`, stableId: id => `ID estable del tablero: ${id}`, replay: 'Repetir este tablero' },
  fr: { title: 'Collection de grilles de Casey', unplayed: 'Pas encore jouée', cityBest: tier => `Médaille de la ville : ${tier}`, nextPrimary: number => `Prochaine grille principale : ${number}`, primaryComplete: 'Toutes les grilles principales sont terminées. Améliore une grille en la rejouant.', primaryWaiting: 'Une reprise est ouverte. Ta grille principale attend sans changer.', boardAria: (number, tier) => `Grille ${number} : ${tier}`, pagerAria: 'Pages de la collection de grilles', details: number => `Détails de la grille ${number}`, stableId: id => `ID stable de la grille : ${id}`, replay: 'Rejouer cette grille' },
  pt: { title: 'Coleção de tabuleiros da Casey', unplayed: 'Por jogar', cityBest: tier => `Medalha da cidade: ${tier}`, nextPrimary: number => `Próximo tabuleiro principal: ${number}`, primaryComplete: 'Todos os tabuleiros principais estão concluídos. Melhora um tabuleiro numa repetição.', primaryWaiting: 'Há uma repetição aberta. O teu tabuleiro principal espera sem mudanças.', boardAria: (number, tier) => `Tabuleiro ${number}: ${tier}`, pagerAria: 'Páginas da coleção de tabuleiros', details: number => `Detalhes do tabuleiro ${number}`, stableId: id => `ID estável do tabuleiro: ${id}`, replay: 'Repetir este tabuleiro' },
  nl: { title: 'Caseys bordenverzameling', unplayed: 'Nog niet gespeeld', cityBest: tier => `Stadsmedaille: ${tier}`, nextPrimary: number => `Volgend hoofdbord: ${number}`, primaryComplete: 'Alle hoofdborden zijn voltooid. Verbeter een bord met een herhaling.', primaryWaiting: 'Er staat een herhaling open. Je hoofdbord wacht ongewijzigd.', boardAria: (number, tier) => `Bord ${number}: ${tier}`, pagerAria: 'Pagina’s van de bordenverzameling', details: number => `Details van bord ${number}`, stableId: id => `Stabiele bord-ID: ${id}`, replay: 'Dit bord herhalen' },
  pl: { title: 'Kolekcja plansz Casey', unplayed: 'Nierozegrana', cityBest: tier => `Medal miasta: ${tier}`, nextPrimary: number => `Następna główna plansza: ${number}`, primaryComplete: 'Wszystkie główne plansze są ukończone. Popraw planszę w powtórce.', primaryWaiting: 'Powtórka jest otwarta. Twoja główna plansza czeka bez zmian.', boardAria: (number, tier) => `Plansza ${number}: ${tier}`, pagerAria: 'Strony kolekcji plansz', details: number => `Szczegóły planszy ${number}`, stableId: id => `Stały identyfikator planszy: ${id}`, replay: 'Powtórz tę planszę' },
  sv: { title: 'Caseys brädsamling', unplayed: 'Ospelat', cityBest: tier => `Stadsmedalj: ${tier}`, nextPrimary: number => `Nästa huvudbräde: ${number}`, primaryComplete: 'Alla huvudbräden är klara. Förbättra ett bräde genom att spela om det.', primaryWaiting: 'En repris är öppen. Ditt huvudbräde väntar oförändrat.', boardAria: (number, tier) => `Bräde ${number}: ${tier}`, pagerAria: 'Sidor i brädsamlingen', details: number => `Detaljer för bräde ${number}`, stableId: id => `Stabilt bräd-ID: ${id}`, replay: 'Spela om det här brädet' },
  nb: { title: 'Caseys brettsamling', unplayed: 'Ikke spilt', cityBest: tier => `Bymedalje: ${tier}`, nextPrimary: number => `Neste hovedbrett: ${number}`, primaryComplete: 'Alle hovedbrett er fullført. Forbedre et brett med en reprise.', primaryWaiting: 'En reprise er åpen. Hovedbrettet ditt venter uendret.', boardAria: (number, tier) => `Brett ${number}: ${tier}`, pagerAria: 'Sider i brettsamlingen', details: number => `Detaljer for brett ${number}`, stableId: id => `Stabil brett-ID: ${id}`, replay: 'Spill dette brettet igjen' },
  hu: { title: 'Casey táblagyűjteménye', unplayed: 'Még nem játszott', cityBest: tier => `Városi érem: ${tier}`, nextPrimary: number => `Következő főtábla: ${number}`, primaryComplete: 'Minden főtábla kész. Javíts egy táblát újrajátszással.', primaryWaiting: 'Egy újrajátszás nyitva van. A főtáblád változatlanul vár.', boardAria: (number, tier) => `Tábla ${number}: ${tier}`, pagerAria: 'A táblagyűjtemény oldalai', details: number => `${number}. tábla részletei`, stableId: id => `Állandó táblaazonosító: ${id}`, replay: 'Tábla újrajátszása' },
  zh: { title: 'Casey 的棋盘收藏', unplayed: '尚未游玩', cityBest: tier => `城市奖牌：${tier}`, nextPrimary: number => `下一主棋盘：${number}`, primaryComplete: '所有主棋盘均已完成。通过重玩来提升棋盘成绩。', primaryWaiting: '重玩已打开。你的主棋盘保持不变，正在等待。', boardAria: (number, tier) => `棋盘 ${number}：${tier}`, pagerAria: '棋盘收藏分页', details: number => `棋盘 ${number} 的详情`, stableId: id => `稳定棋盘 ID：${id}`, replay: '重玩此棋盘' },
}

export const COLLECTION_UI = copies[UI_LANGUAGE] ?? copies.en
