import { UI_LANGUAGE } from './active'
import type { UiLanguage } from './types'

type ReceiptCopy = {
  title: string; solved: string; tier: string; personalBest: string
  bestChange: (before: string, after: string) => string; firstBest: (tier: string) => string
  rewards: string; eligible: (items: string) => string; alreadyEarned: (items: string) => string
  newPostcards: (count: number) => string; none: string
  spinWin: string; solvedReward: string; solvedAndTranslated: string
  bronze: string; silver: string; gold: string; platinum: string
  learning: string; learningNone: string; learningNew: string
  learningState: (box: number, seen: number, correct: number, misses: number, lookups: number, clues: number, guesses: number) => string
  learningChange: (word: string, before: string, after: string) => string
}

type FinishHeaderCopy = {
  goodGame: string; greatGame: string; perfectGame: string; participationTrophy: string
  rewardSpin: string; rewardSolved: string; rewardTranslated: string
  noRewards: string; alreadyEarnedLabel: string; participationOnly: string
  /** The finish header's small line: which board, and what the screen is. */
  boardLabel: (n: string) => string; resultLabel: string
}

const finishHeaderCopies: Record<UiLanguage, FinishHeaderCopy> = {
  en: { goodGame: 'Good game!', greatGame: 'Great game!', perfectGame: 'Perfect game!', participationTrophy: 'Participation trophy', rewardSpin: 'spin and win', rewardSolved: 'found every word', rewardTranslated: 'found and translated every word', noRewards: 'No postcard rewards', alreadyEarnedLabel: 'Already earned', participationOnly: 'participation only', boardLabel: n => `Board ${n}`, resultLabel: 'Result' },
  de: { goodGame: 'Gut gespielt!', greatGame: 'Stark gespielt!', perfectGame: 'Perfekt gespielt!', participationTrophy: 'Teilnahme-Trophäe', rewardSpin: 'Dreh gewonnen', rewardSolved: 'alle Wörter gefunden', rewardTranslated: 'alle Wörter gefunden und übersetzt', noRewards: 'Keine Postkartenbelohnungen', alreadyEarnedLabel: 'Bereits verdient', participationOnly: 'nur zur Teilnahme', boardLabel: n => `Brett ${n}`, resultLabel: 'Ergebnis' },
  es: { goodGame: '¡Buen juego!', greatGame: '¡Gran partida!', perfectGame: '¡Partida perfecta!', participationTrophy: 'Trofeo de participación', rewardSpin: 'ruleta ganada', rewardSolved: 'encontrar todas las palabras', rewardTranslated: 'encontrar y traducir todas las palabras', noRewards: 'Sin recompensas de postales', alreadyEarnedLabel: 'Ya conseguido', participationOnly: 'solo por participar', boardLabel: n => `Tablero ${n}`, resultLabel: 'Resultado' },
  fr: { goodGame: 'Belle partie !', greatGame: 'Super partie !', perfectGame: 'Partie parfaite !', participationTrophy: 'Trophée de participation', rewardSpin: 'roue gagnée', rewardSolved: 'tous les mots trouvés', rewardTranslated: 'tous les mots trouvés et traduits', noRewards: 'Aucune récompense de carte postale', alreadyEarnedLabel: 'Déjà obtenu', participationOnly: 'participation uniquement', boardLabel: n => `Grille ${n}`, resultLabel: 'Résultat' },
  hu: { goodGame: 'Szép játék!', greatGame: 'Nagyszerű játék!', perfectGame: 'Tökéletes játék!', participationTrophy: 'Részvételi trófea', rewardSpin: 'nyerés a szerencsekeréken', rewardSolved: 'minden szó megtalálása', rewardTranslated: 'minden szó megtalálása és lefordítása', noRewards: 'Nincs képeslapjutalom', alreadyEarnedLabel: 'Már megszerzett', participationOnly: 'csak részvétel', boardLabel: n => `Tábla ${n}`, resultLabel: 'Eredmény' },
  nb: { goodGame: 'Bra spilt!', greatGame: 'Flott spilt!', perfectGame: 'Perfekt spilt!', participationTrophy: 'Deltakertrofé', rewardSpin: 'vunnet på lykkehjulet', rewardSolved: 'funnet alle ordene', rewardTranslated: 'funnet og oversatt alle ordene', noRewards: 'Ingen postkortbelønninger', alreadyEarnedLabel: 'Allerede opptjent', participationOnly: 'kun deltakelse', boardLabel: n => `Brett ${n}`, resultLabel: 'Resultat' },
  nl: { goodGame: 'Goed gespeeld!', greatGame: 'Geweldig gespeeld!', perfectGame: 'Perfect gespeeld!', participationTrophy: 'Deelnametrofee', rewardSpin: 'draai gewonnen', rewardSolved: 'alle woorden gevonden', rewardTranslated: 'alle woorden gevonden en vertaald', noRewards: 'Geen ansichtkaartbeloningen', alreadyEarnedLabel: 'Al verdiend', participationOnly: 'alleen voor deelname', boardLabel: n => `Bord ${n}`, resultLabel: 'Resultaat' },
  pl: { goodGame: 'Dobra gra!', greatGame: 'Świetna gra!', perfectGame: 'Perfekcyjna gra!', participationTrophy: 'Trofeum za udział', rewardSpin: 'wygrana na kole', rewardSolved: 'znalezienie wszystkich słów', rewardTranslated: 'znalezienie i przetłumaczenie wszystkich słów', noRewards: 'Brak nagród pocztówkowych', alreadyEarnedLabel: 'Już zdobyte', participationOnly: 'tylko za udział', boardLabel: n => `Plansza ${n}`, resultLabel: 'Wynik' },
  pt: { goodGame: 'Bom jogo!', greatGame: 'Grande jogo!', perfectGame: 'Jogo perfeito!', participationTrophy: 'Troféu de participação', rewardSpin: 'vitória na roleta', rewardSolved: 'encontrar todas as palavras', rewardTranslated: 'encontrar e traduzir todas as palavras', noRewards: 'Sem recompensas de postais', alreadyEarnedLabel: 'Já obtido', participationOnly: 'apenas participação', boardLabel: n => `Tabuleiro ${n}`, resultLabel: 'Resultado' },
  sv: { goodGame: 'Bra spelat!', greatGame: 'Riktigt bra spelat!', perfectGame: 'Perfekt spelat!', participationTrophy: 'Deltagarpokal', rewardSpin: 'vinst på hjulet', rewardSolved: 'hittat alla ord', rewardTranslated: 'hittat och översatt alla ord', noRewards: 'Inga vykortsbelöningar', alreadyEarnedLabel: 'Redan intjänat', participationOnly: 'endast deltagande', boardLabel: n => `Bräde ${n}`, resultLabel: 'Resultat' },
  zh: { goodGame: '玩得好！', greatGame: '精彩表现！', perfectGame: '完美一局！', participationTrophy: '参与奖杯', rewardSpin: '转盘获胜', rewardSolved: '找到所有单词', rewardTranslated: '找到并翻译所有单词', noRewards: '没有明信片奖励', alreadyEarnedLabel: '已获得', participationOnly: '仅表示参与', boardLabel: n => `棋盘 ${n}`, resultLabel: '结果' },
}

const copies: Record<string, ReceiptCopy> = {
  en: { title: 'This attempt', solved: 'Solved the board', tier: 'Attempt tier', personalBest: 'Personal best', bestChange: (before, after) => `${before} → ${after}`, firstBest: tier => `First result: ${tier}`, rewards: 'Postcard rewards', eligible: items => `This attempt qualifies for: ${items}`, alreadyEarned: items => `Already earned: ${items}`, newPostcards: count => count === 1 ? '+1 new postcard' : `+${count} new postcards`, none: 'none', spinWin: 'wheel win', solvedReward: 'solved board', solvedAndTranslated: 'solved and translated', bronze: 'Bronze', silver: 'Silver', gold: 'Gold', platinum: 'Platinum', learning: 'Word learning', learningNone: 'No word-learning records changed in this attempt.', learningNew: 'new record', learningState: (box, seen, correct, misses, lookups, clues, guesses) => `box ${box}; seen ${seen}; correct ${correct}; misses ${misses}; lookups ${lookups}; clue greens ${clues}; guess greens ${guesses}`, learningChange: (word, before, after) => `${word}: ${before} → ${after}` },
  de: { title: 'Dieser Versuch', solved: 'Das Brett gelöst', tier: 'Versuchsstufe', personalBest: 'Persönliche Bestleistung', bestChange: (before, after) => `${before} → ${after}`, firstBest: tier => `Erstes Ergebnis: ${tier}`, rewards: 'Postkarten-Belohnungen', eligible: items => `Dieser Versuch berechtigt zu: ${items}`, alreadyEarned: items => `Schon verdient: ${items}`, newPostcards: count => count === 1 ? '+1 neue Postkarte' : `+${count} neue Postkarten`, none: 'keine', spinWin: 'Glücksrad gewonnen', solvedReward: 'Brett gelöst', solvedAndTranslated: 'gelöst und übersetzt', bronze: 'Bronze-Stufe', silver: 'Silber-Stufe', gold: 'Gold-Stufe', platinum: 'Platin-Stufe', learning: 'Wortlernen', learningNone: 'In diesem Versuch wurden keine Wortlernwerte geändert.', learningNew: 'neuer Eintrag', learningState: (box, seen, correct, misses, lookups, clues, guesses) => `Fach ${box}; gesehen ${seen}; richtig ${correct}; Fehler ${misses}; Nachschlagen ${lookups}; Hinweis-Grün ${clues}; Rate-Grün ${guesses}`, learningChange: (word, before, after) => `${word}: ${before} → ${after}` },
  es: { title: 'Este intento', solved: 'Tablero resuelto', tier: 'Nivel del intento', personalBest: 'Mejor marca personal', bestChange: (before, after) => `${before} → ${after}`, firstBest: tier => `Primer resultado: ${tier}`, rewards: 'Recompensas de postales', eligible: items => `Este intento cumple para: ${items}`, alreadyEarned: items => `Ya conseguido: ${items}`, newPostcards: count => count === 1 ? '+1 postal nueva' : `+${count} postales nuevas`, none: 'ninguna', spinWin: 'ruleta ganada', solvedReward: 'tablero resuelto', solvedAndTranslated: 'resuelto y traducido', bronze: 'nivel bronce', silver: 'nivel plata', gold: 'nivel oro', platinum: 'nivel platino', learning: 'Aprendizaje de palabras', learningNone: 'No cambió ningún registro de aprendizaje de palabras en este intento.', learningNew: 'registro nuevo', learningState: (box, seen, correct, misses, lookups, clues, guesses) => `caja ${box}; vistas ${seen}; aciertos ${correct}; fallos ${misses}; consultas ${lookups}; verdes por pista ${clues}; verdes por respuesta ${guesses}`, learningChange: (word, before, after) => `${word}: ${before} → ${after}` },
  fr: { title: 'Cette tentative', solved: 'Grille résolue', tier: 'Niveau de la tentative', personalBest: 'Meilleur résultat personnel', bestChange: (before, after) => `${before} → ${after}`, firstBest: tier => `Premier résultat : ${tier}`, rewards: 'Récompenses de cartes postales', eligible: items => `Cette tentative donne droit à : ${items}`, alreadyEarned: items => `Déjà obtenu : ${items}`, newPostcards: count => count === 1 ? '+1 nouvelle carte postale' : `+${count} nouvelles cartes postales`, none: 'aucune', spinWin: 'roue gagnée', solvedReward: 'grille résolue', solvedAndTranslated: 'résolue et traduite', bronze: 'niveau bronze', silver: 'niveau argent', gold: 'niveau or', platinum: 'niveau platine', learning: 'Apprentissage des mots', learningNone: 'Aucun relevé d’apprentissage des mots n’a changé dans cette tentative.', learningNew: 'nouveau relevé', learningState: (box, seen, correct, misses, lookups, clues, guesses) => `boîte ${box} ; vues ${seen} ; correctes ${correct} ; erreurs ${misses} ; recherches ${lookups} ; verts par indice ${clues} ; verts par réponse ${guesses}`, learningChange: (word, before, after) => `${word} : ${before} → ${after}` },
  hu: { title: 'Ez a próbálkozás', solved: 'A tábla megoldva', tier: 'Próbálkozási szint', personalBest: 'Személyes legjobb', bestChange: (before, after) => `${before} → ${after}`, firstBest: tier => `Első eredmény: ${tier}`, rewards: 'Képeslapjutalmak', eligible: items => `Ez a próbálkozás jogosít: ${items}`, alreadyEarned: items => `Már megszerzett: ${items}`, newPostcards: count => count === 1 ? '+1 új képeslap' : `+${count} új képeslap`, none: 'nincs', spinWin: 'kerékgyőzelem', solvedReward: 'megoldott tábla', solvedAndTranslated: 'megoldott és lefordított', bronze: 'bronz szint', silver: 'ezüst szint', gold: 'arany szint', platinum: 'platina szint', learning: 'Szótanulás', learningNone: 'Ebben a próbálkozásban nem változott szótanulási adat.', learningNew: 'új bejegyzés', learningState: (box, seen, correct, misses, lookups, clues, guesses) => `doboz ${box}; látva ${seen}; helyes ${correct}; hibák ${misses}; keresések ${lookups}; zöld nyomból ${clues}; zöld tippből ${guesses}`, learningChange: (word, before, after) => `${word}: ${before} → ${after}` },
  nb: { title: 'Dette forsøket', solved: 'Brettet er løst', tier: 'Forsøksnivå', personalBest: 'Personlig rekord', bestChange: (before, after) => `${before} → ${after}`, firstBest: tier => `Første resultat: ${tier}`, rewards: 'Postkortbelønninger', eligible: items => `Dette forsøket kvalifiserer for: ${items}`, alreadyEarned: items => `Allerede opptjent: ${items}`, newPostcards: count => count === 1 ? '+1 nytt postkort' : `+${count} nye postkort`, none: 'ingen', spinWin: 'hjulseier', solvedReward: 'løst brett', solvedAndTranslated: 'løst og oversatt', bronze: 'bronsenivå', silver: 'sølvnivå', gold: 'gullnivå', platinum: 'platina-nivå', learning: 'Ordlæring', learningNone: 'Ingen ordlæringsposter ble endret i dette forsøket.', learningNew: 'ny post', learningState: (box, seen, correct, misses, lookups, clues, guesses) => `boks ${box}; sett ${seen}; riktig ${correct}; feil ${misses}; oppslag ${lookups}; grønne via ledetråd ${clues}; grønne via gjetning ${guesses}`, learningChange: (word, before, after) => `${word}: ${before} → ${after}` },
  nl: { title: 'Deze poging', solved: 'Bord opgelost', tier: 'Pogingniveau', personalBest: 'Persoonlijk beste', bestChange: (before, after) => `${before} → ${after}`, firstBest: tier => `Eerste resultaat: ${tier}`, rewards: 'Ansichtkaartbeloningen', eligible: items => `Deze poging komt in aanmerking voor: ${items}`, alreadyEarned: items => `Al verdiend: ${items}`, newPostcards: count => count === 1 ? '+1 nieuwe ansichtkaart' : `+${count} nieuwe ansichtkaarten`, none: 'geen', spinWin: 'wiel gewonnen', solvedReward: 'bord opgelost', solvedAndTranslated: 'opgelost en vertaald', bronze: 'bronsniveau', silver: 'zilverniveau', gold: 'goudniveau', platinum: 'platinaniveau', learning: 'Woordleren', learningNone: 'Er veranderde geen woordleerrecord in deze poging.', learningNew: 'nieuw record', learningState: (box, seen, correct, misses, lookups, clues, guesses) => `vak ${box}; gezien ${seen}; goed ${correct}; missers ${misses}; opgezocht ${lookups}; groen via hint ${clues}; groen via gok ${guesses}`, learningChange: (word, before, after) => `${word}: ${before} → ${after}` },
  pl: { title: 'Ta próba', solved: 'Plansza rozwiązana', tier: 'Poziom próby', personalBest: 'Najlepszy wynik', bestChange: (before, after) => `${before} → ${after}`, firstBest: tier => `Pierwszy wynik: ${tier}`, rewards: 'Nagrody pocztówkowe', eligible: items => `Ta próba kwalifikuje do: ${items}`, alreadyEarned: items => `Już zdobyte: ${items}`, newPostcards: count => count === 1 ? '+1 nowa pocztówka' : `+${count} nowych pocztówek`, none: 'brak', spinWin: 'wygrana ruleta', solvedReward: 'rozwiązana plansza', solvedAndTranslated: 'rozwiązana i przetłumaczona', bronze: 'poziom brązowy', silver: 'poziom srebrny', gold: 'poziom złoty', platinum: 'poziom platynowy', learning: 'Nauka słów', learningNone: 'W tej próbie nie zmienił się żaden zapis nauki słów.', learningNew: 'nowy zapis', learningState: (box, seen, correct, misses, lookups, clues, guesses) => `pudełko ${box}; widziane ${seen}; poprawne ${correct}; błędy ${misses}; sprawdzenia ${lookups}; zielone po wskazówce ${clues}; zielone po zgadnięciu ${guesses}`, learningChange: (word, before, after) => `${word}: ${before} → ${after}` },
  pt: { title: 'Esta tentativa', solved: 'Tabuleiro resolvido', tier: 'Nível da tentativa', personalBest: 'Melhor resultado pessoal', bestChange: (before, after) => `${before} → ${after}`, firstBest: tier => `Primeiro resultado: ${tier}`, rewards: 'Recompensas de postais', eligible: items => `Esta tentativa qualifica para: ${items}`, alreadyEarned: items => `Já obtido: ${items}`, newPostcards: count => count === 1 ? '+1 postal novo' : `+${count} postais novos`, none: 'nenhuma', spinWin: 'roda ganha', solvedReward: 'tabuleiro resolvido', solvedAndTranslated: 'resolvido e traduzido', bronze: 'nível bronze', silver: 'nível prata', gold: 'nível ouro', platinum: 'nível platina', learning: 'Aprendizagem de palavras', learningNone: 'Nenhum registo de aprendizagem de palavras mudou nesta tentativa.', learningNew: 'novo registo', learningState: (box, seen, correct, misses, lookups, clues, guesses) => `caixa ${box}; vistas ${seen}; certas ${correct}; falhas ${misses}; consultas ${lookups}; verdes por pista ${clues}; verdes por palpite ${guesses}`, learningChange: (word, before, after) => `${word}: ${before} → ${after}` },
  sv: { title: 'Det här försöket', solved: 'Brädet är löst', tier: 'Försöksnivå', personalBest: 'Personbästa', bestChange: (before, after) => `${before} → ${after}`, firstBest: tier => `Första resultatet: ${tier}`, rewards: 'Vykortsbelöningar', eligible: items => `Det här försöket ger: ${items}`, alreadyEarned: items => `Redan intjänat: ${items}`, newPostcards: count => count === 1 ? '+1 nytt vykort' : `+${count} nya vykort`, none: 'inga', spinWin: 'hjulvinst', solvedReward: 'löst bräde', solvedAndTranslated: 'löst och översatt', bronze: 'bronsnivå', silver: 'silvernivå', gold: 'guldnivå', platinum: 'platinanivå', learning: 'Ordinlärning', learningNone: 'Inga ordinlärningsposter ändrades i det här försöket.', learningNew: 'ny post', learningState: (box, seen, correct, misses, lookups, clues, guesses) => `ruta ${box}; sedd ${seen}; rätt ${correct}; fel ${misses}; uppslag ${lookups}; gröna via ledtråd ${clues}; gröna via gissning ${guesses}`, learningChange: (word, before, after) => `${word}: ${before} → ${after}` },
  zh: { title: '本次尝试', solved: '已解开棋盘', tier: '本次等级', personalBest: '个人最佳', bestChange: (before, after) => `${before} → ${after}`, firstBest: tier => `首次结果：${tier}`, rewards: '明信片奖励', eligible: items => `本次可获得：${items}`, alreadyEarned: items => `已经获得：${items}`, newPostcards: count => `+${count} 张新明信片`, none: '无', spinWin: '转盘获胜', solvedReward: '解开棋盘', solvedAndTranslated: '解开并翻译', bronze: '铜牌等级', silver: '银牌等级', gold: '金牌等级', platinum: '白金等级', learning: '单词学习', learningNone: '本次尝试没有改变单词学习记录。', learningNew: '新记录', learningState: (box, seen, correct, misses, lookups, clues, guesses) => `盒 ${box}；见过 ${seen}；正确 ${correct}；错误 ${misses}；查阅 ${lookups}；线索绿色 ${clues}；猜测绿色 ${guesses}`, learningChange: (word, before, after) => `${word}：${before} → ${after}` },
}

/** C1-11's deferred result catalogue; all 11 interface languages live here so
 * the ordinary offline shell does not carry a result screen until it is used. */
export const RECEIPT_UI = {
  ...(copies[UI_LANGUAGE] ?? copies.en),
  ...(finishHeaderCopies[UI_LANGUAGE] ?? finishHeaderCopies.en),
}
