// Generated by scripts/generate-worker-german.mjs. Edit the pure src/lang/de rules, then regenerate.

// src/lang/de/prompts.ts
var translateRules = `- Give the citation form: a noun in the nominative singular WITH ITS CAPITAL LETTER, a verb as the bare infinitive in lower case, an adjective in its uninflected form.
- For a NOUN, always give the gender: "masculine" (der), "feminine" (die) or "neuter" (das). Give "article" as well ONLY when the noun has an ordinary indefinite singular \u2014 most do. Note that masculine and neuter nouns BOTH take "ein"; only feminine takes "eine".
- Mass and abstract nouns do not: nobody says "eine Milch", "ein Blut", "eine Liebe", "ein Verkehr". For those set "countable": false and give the gender with no article.
- Where BOTH readings are ordinary German the noun IS countable and keeps its article \u2014 "ein Bier", "ein Brot" (a loaf), "ein Eis", "ein Wasser" and "ein Kaffee" are all things people order, so do not strip those.

Respond with ONLY a JSON object: {"da": string, "en": string, "article": "ein" | "eine" (countable nouns only), "gender": "masculine" | "feminine" | "neuter" (all nouns), "countable": boolean (nouns only), "note": string (optional)}

Example for "Fahrrad": {"da": "Fahrrad", "en": "bicycle", "article": "ein", "gender": "neuter", "countable": true}
Example for "afternoon": {"da": "Nachmittag", "en": "afternoon", "article": "ein", "gender": "masculine", "countable": true}
Example for "Verkehr": {"da": "Verkehr", "en": "traffic", "gender": "masculine", "countable": false}
Example for "to cycle": {"da": "fahren", "en": "to cycle"}`;
var germanPrompts = {
  translateRules,
  spellingRule: "Write German with \xE4, \xF6, \xFC and \xDF \u2014 never ae, oe, ue or ss. Capitalise every noun.",
  functionWordNote: "auf, an, aus, mit, doch, mal, schon, eben, gleich, noch, wieder and the like. Association clues do not reach these, so never hang one on the back of a real clue. Take one only alone, with number 1, pointing at the everyday phrase it lives in (aufstehen, noch einmal, gerade jetzt)",
  clueExampleWord: "Haustier",
  // Player-language rationale examples now belong to the player-language layer.
  compoundExample: 'with "Zimmer" on the board, "Schlafzimmer" is illegal'
};

// src/engine/text.ts
function normalize(s) {
  return s.normalize("NFC").trim().toLowerCase();
}

// src/lang/de/orthography.ts
var fold = (s) => s.replace(/ä/g, "ae").replace(/ö/g, "oe").replace(/ü/g, "ue").replace(/ß/g, "ss");
var unfold = (s) => s.replace(/ae/g, "\xE4").replace(/oe/g, "\xF6").replace(/ue/g, "\xFC");
var germanOrthography = {
  distinctive: /[äöüß]/,
  fold,
  unfold,
  // TRUE, and this is the case the flag exists for. "ss" for "ß" is correct
  // Swiss orthography and "ue" for "ü" is an accepted transcription, so a
  // folded match here may be the word spelled correctly rather than a typo to
  // forgive. The packing grader asks this rather than assuming; Danish answers
  // false, because nobody writes "oel" for "øl".
  foldsAreSpellings: true
};

// src/lang/de/legality.ts
var fold2 = germanOrthography.fold;
var bareVowel = (s) => s.replace(/ä|ae/g, "a").replace(/ö|oe/g, "o").replace(/ü|ue/g, "u");
var ENDINGS = ["esten", "este", "sten", "ste", "ern", "ten", "end", "em", "en", "er", "es", "et", "st", "te", "e", "n", "s", "t"];
var UMLAUT_ENDINGS = /* @__PURE__ */ new Set(["esten", "este", "sten", "ste", "ern", "en", "er", "e"]);
var TAILS = new Set(ENDINGS);
var SUFFIXES = /* @__PURE__ */ new Set(["schaft", "schaften", "heit", "heiten", "keit", "keiten", "ung", "ungen", "tum", "nis", "nisse", "chen", "lein", "lich", "liche", "isch", "ische", "los", "lose", "bar", "bare", "haft", "hafte", "sam", "same", "voll", "volle", "frei", "freie", "erei", "ling", "linge", "werk", "zeug"]);
var LINKERS = ["", "s", "es", "n", "en", "ns", "e", "er"];
var PREFIXES = ["zusammen", "zur\xFCck", "zurueck", "entgegen", "herunter", "hinunter", "heraus", "herein", "hinaus", "hinein", "weiter", "wieder", "voraus", "vorbei", "davon", "durch", "statt", "unter", "gegen", "empor", "nieder", "fest", "fort", "heim", "nach", "\xFCber", "ueber", "teil", "voll", "dazu", "zer", "auf", "aus", "bei", "ein", "ent", "her", "hin", "los", "mit", "ver", "vor", "weg", "ab", "an", "be", "er", "um", "zu"];
var IRREGULAR = [
  ["gehen", "gegangen"],
  ["stehen", "gestanden"],
  ["nehmen", "genommen"],
  ["finden", "gefunden"],
  ["sitzen", "gesessen"],
  ["liegen", "gelegen"],
  ["denken", "gedacht"],
  ["wissen", "gewusst"],
  ["bringen", "gebracht"],
  ["essen", "gegessen"],
  ["treffen", "getroffen"],
  ["sprechen", "gesprochen"],
  ["sein", "gewesen"],
  ["haben", "gehabt"],
  ["werden", "geworden"],
  ["gut", "besser"],
  ["gut", "beste"],
  ["viel", "mehr"],
  ["viel", "meiste"],
  ["nehmen", "nimmt"],
  ["sehen", "sieht"],
  ["essen", "isst"],
  ["lesen", "liest"],
  ["fahren", "f\xE4hrt"],
  ["halten", "h\xE4lt"],
  ["laufen", "l\xE4uft"],
  ["mutter", "m\xFCtter"],
  ["tochter", "t\xF6chter"],
  ["bruder", "br\xFCder"]
];
var LATINATE = /^.{3,}ier(en|t|te|ten|st)$/;
var LATINATE_WORD = /(ation|ition|ution|ktion|sion|ismus|ität|itaet)$/;
var FRAGMENT = /^(ver|vor|be|ge|ent|er|zer|emp|miss|um|un)[bcdfghjklmnpqrstvwxzß]{1,2}$/;
var freeMorpheme = (s, floor) => s.length >= floor && /[aeiouyäöü]/.test(s) && !FRAGMENT.test(s) && !TAILS.has(s);
function constituents(board, pos) {
  const stem = board.endsWith("en") ? board.slice(0, -2) : board.endsWith("n") ? board.slice(0, -1) : board;
  return pos === "verb" && stem.length >= 4 && stem !== board ? [board, stem] : [board];
}
function hasConstituent(compound, part, floor) {
  if (part.length < floor || compound.length <= part.length) return false;
  if (compound.startsWith(part)) {
    const rest = compound.slice(part.length);
    for (const linker of LINKERS) {
      if (!rest.startsWith(linker)) continue;
      const head = rest.slice(linker.length);
      if (!LATINATE.test(head) && (SUFFIXES.has(head) || freeMorpheme(head, floor))) return true;
    }
  }
  if (compound.endsWith(part)) {
    const rest = compound.slice(0, -part.length);
    for (const linker of LINKERS) {
      if (!rest.endsWith(linker)) continue;
      const modifier = rest.slice(0, rest.length - linker.length);
      if (modifier.length === 3 && part.length < 4) continue;
      if (freeMorpheme(modifier, floor)) return true;
    }
  }
  return false;
}
function endingForm(longer, targets, umlaut = true) {
  if (longer.length < 4) return false;
  for (const ending of ENDINGS) {
    if (!longer.endsWith(ending)) continue;
    const base = longer.slice(0, -ending.length);
    if (base.length < 3) continue;
    if (targets.some((target) => base === target || umlaut && UMLAUT_ENDINGS.has(ending) && bareVowel(base) === bareVowel(target))) return true;
  }
  return false;
}
function prefixed(clue, board, pos) {
  for (const prefix of PREFIXES) {
    if (!clue.startsWith(prefix)) continue;
    const rest = clue.slice(prefix.length);
    if (rest.length < 3) continue;
    if (rest === board) return true;
    if (pos === "verb" && endingForm(rest, constituents(board, pos), false)) return true;
  }
  return false;
}
function compoundOf(clue, board, pos) {
  const floor = 3;
  const check = (a, b) => hasConstituent(a, b, floor);
  for (const part of constituents(board, pos)) {
    if (part !== board && LATINATE_WORD.test(clue)) continue;
    if (check(clue, part) || check(part, clue)) return true;
    if (clue === fold2(clue) && check(clue, fold2(part))) return true;
    if (part === fold2(part) && check(part, fold2(clue))) return true;
  }
  return prefixed(clue, board, pos) || prefixed(board, clue, pos);
}
function formOf(clue, board, pos) {
  for (const c of /* @__PURE__ */ new Set([clue, fold2(clue)])) {
    for (const b of /* @__PURE__ */ new Set([board, fold2(board)])) {
      if (endingForm(c, constituents(b, pos), pos !== "verb") || endingForm(b, [c], pos !== "verb")) return true;
      if (pos === "noun" && /(er|el|en)$/.test(b) && bareVowel(c) === bareVowel(b)) return true;
      if (pos === "verb" && c.startsWith("ge") && c.length >= 6) {
        const stem = b.endsWith("en") ? b.slice(0, -2) : b.endsWith("n") ? b.slice(0, -1) : b;
        if (stem.length >= 3 && ["t", "et", "en"].some((suffix) => c.slice(2) === stem + suffix)) return true;
      }
      if (IRREGULAR.some(([a, z]) => c === a && b === z || c === z && b === a)) return true;
    }
  }
  return false;
}
var SHORT_INFLECTIONS = /* @__PURE__ */ new Set(["e", "n", "r", "s", "t", "en", "er", "es", "em", "et", "st", "ern", "te", "ten"]);
function inflectionOfShort(longer, short) {
  if (short.length > 3 || !longer.startsWith(short)) return false;
  let rest = longer.slice(short.length);
  if (rest[0] === short[short.length - 1]) rest = rest.slice(1);
  return SHORT_INFLECTIONS.has(rest);
}
function checkGermanClueLegality(clue, words) {
  const candidate = normalize(clue);
  if (!candidate) return { legal: false, reason: "empty clue", why: { kind: "empty" } };
  if (/\s/.test(candidate)) return { legal: false, reason: "clue must be a single word", why: { kind: "not-single-word" } };
  for (const word of words) {
    const board = normalize(word.da);
    if (!board) continue;
    if (candidate === board || fold2(candidate) === fold2(board)) return {
      legal: false,
      conflictWord: word.da,
      reason: `"${clue}" is a word on the board`,
      why: { kind: "on-board", clue }
    };
    if (compoundOf(candidate, board, word.pos)) return {
      legal: false,
      conflictWord: word.da,
      reason: `"${clue}" is a compound of "${word.da}"`,
      why: { kind: "compound-of", clue, candidate: word.da }
    };
    if (formOf(candidate, board, word.pos) || inflectionOfShort(candidate, board) || inflectionOfShort(board, candidate)) return {
      legal: false,
      conflictWord: word.da,
      reason: `"${clue}" is a form of "${word.da}"`,
      why: { kind: "form-of", clue, candidate: word.da }
    };
  }
  return { legal: true };
}

// <stdin>
var GERMAN_LANGUAGE = {
  code: "de",
  name: "German",
  prompts: germanPrompts,
  checkClueLegality: checkGermanClueLegality
};
export {
  GERMAN_LANGUAGE
};
